### ISSUE TITLE
Respect original formatting/whitespace

### ISSUE THREAD

**Issue by rbren** [mangiucugna/json_repair#18]
**Describe the bug**
(This might be too hard and out of scope depending on the implementation. If so, feel free to close)

The repair removes whitespace, so that if the LLM responds with:
```json
{
  "foo": "bar"
}
```
repair "corrects" it to
```json
{"foo":"bar"}
```

This makes it hard to detect if an _actual_ repair was made.

**To Reproduce**
repair JSON with whitespace

**Expected behavior**
whitespace is preserved

**Comment by mangiucugna** [comment]
This is an interesting issue because the library isn't stripping whitespaces if not trailing ones, the behavior is the one of json.dumps().
One could argue that I shouldn't "redump" a valid json but that would cause an issue when `return_objects=True` on a valid json. I could fix this by redumping only on `return_objects=True` but you see that it gets kinda complicated :)
