### ISSUE TITLE
Escaping underscores

### ISSUE THREAD

**Issue by rbren** [mangiucugna/json_repair#19]
**Describe the bug**

We have an issue here: https://github.com/OpenDevin/OpenDevin/issues/495

The LLM response tries to escape underscores. So the key `new_monologue` becomes `new\_monologue` in the LLM response. json_repair double-escapes the backslash, instead of removing it.

This behavior, where the LLM attempts to escape underscores, seems not uncommon. Maybe we have a special pattern of replacing `\_` with `_`?

**Expected behavior**
Escape characters removed

**Comment by mangiucugna** [comment]
First of all that json is valid according to the standard BUT json.loads() throws an error while trying to decode it (presumably because a single backslash is invalid in a python string).
Following that:

```
>>> json.dumps({"key\_1":"value"})
'{"key\\\\_1": "value"}'
```

And that is exactly the output you see here

So I suppose you should probably replace this common occurence yourself before it gets touched by any json library..

**Comment by mangiucugna** [comment]
I have release 0.11.0 with this fix, let me now if it fixes your issue

**Comment by rbren** [comment]
🎉 thanks!

I left a comment on the commit--do escaped quotes still work, like
```
{
  "message": "say \"hello world\""
}
```
