### ISSUE TITLE
repair_json incorrectly truncates JSON strings with escaped quotes and commas

### ISSUE THREAD

**Issue by mlxyz** [mangiucugna/json_repair#44]
**Describe the bug**
The valid JSON `{"foo": "bar \"foo\", baz"}` gets turned into the broken JSON `{"foo": "bar \\"foo"}` when using `repair_json`.
I think this is related to the escaped quotes and comma.

**To Reproduce**
1. Call `repair_json('{"foo": "bar \"foo\", baz"}')`
2. Check the output `{"foo": "bar \\"foo"}`

**Expected behavior**
Correct output `{"foo": "bar \"foo\", baz"}`

**Comment by mangiucugna** [comment]
so this is a tough one because if you pass that string to python without using `r""` the string passed is: `{"foo": "bar "foo", baz"}` and the result is correct because it's impossible to know in advance if that comma closes the key/value pair or is part of the string.

if you call `repair_json(r'{"foo": "bar \"foo\", baz"}')` the result is correctly `{"foo": "bar \"foo\", baz"}`

**Comment by mangiucugna** [comment]
I hate escaping problems, I will push a new version in a few minutes with what is hopefully a definitive fix
