### ISSUE TITLE
[Feature Request]: Get multiple valid fixes for an invalid JSON string

### ISSUE THREAD

**Issue by danb27** [mangiucugna/json_repair#52]
### Describe the solution you'd like

Imagine your LLM spits out: 

`{"foo": {"bar": {"baz": 1}, "zig": {"zag": 2}}`

This JSON is missing a bracket. There are two places it could go that would fix the issue: 

```
{"foo": {"bar": {"baz": 1}, "zig": {"zag": 2}}
|-------------------------^--------or---------^|
```

Currently, repair_json.loads() returns the valid JSON with the added closing bracket at the end. But my pydantic model actually requires the other solution. 

So if I could do: 

```
valid_jsons = json_repair.parse_all(invalid_llm_output)
validated_output = None
for valid_json in valid_jsons:
    try:
        validated_output = MyExpectedOutputModel.parse(valid_json)
    except ValidationError:
        continue

if not validated_output:
    ... do something ...
```

### Context

That would help make this in even more powerful tool in avoiding calling the LLM for fixing the JSON.

**Comment by mangiucugna** [comment]
Hi, unfortunately for this specific case, and I think more in general, that is not possible due to the nature of the parser I chose.
The library implements a LL(1) parser, that is a totally natural parser for JSON, and this specific string is completely valid till the very end. 
The parser never encounters any error to fix (you can see this by enabling logging). The string just ends and at that point the parser returns an object that is then converted to JSON.
This is unfortunately a limitation of the model, rewriting everything using an LR parser and then generate multiple solutions would be a massive task.
The alternative is to add the ability to pass a pydantic schema and then parse according to the schema (and return nothing if the schema cannot be met), something that has been floated before but I have avoided so far because it's a lot of work :)

**Comment by danb27** [comment]
Gotcha. I figured there was a good chance it was infeasible, out of scope, or both, but figured I would ask. 

Thanks!
